name: Vulnerability
description: Oh-oh
title: "ğŸ”’ï¸ "
labels: ["ğŸ”’ï¸ Vulnerability"]
assignees:
  - orlowdev
  - datapain
  - tgafiulin
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this security issue request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: E.g. email@example.com
    validations:
      required: false
  - type: textarea
    id: whats-up
    attributes:
      label: What happened?
      description: If you know how to mitigate the issue, please let us know.
      placeholder: Check if the file name includes "DROP ALL DATABASES;"...
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true